interface=wlan0
driver=nl80211
ssid=PotsWorks PisoWifi
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
wpa=2
wpa_passphrase=potsworks123
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
ap_isolate=1
ignore_broadcast_ssid=0
macaddr_acl=0
